### PR TITLE
fix: improve regex matching

### PR DESCRIPTION
**Pull request by ben-wilson-peak**
Github comments can appear as \r\n, this improves the regex to support that new requirement

### CODE REVIEW

**Comment by ben-wilson-peak** [comment]
@bkeepers would you be willing to review this?

**Comment by ben-wilson-peak** [comment]
@gr2m do you know who could be a reviewer for this?

**Comment by gr2m** [comment]
sorry we are very short on maintenance time on @probot right now, and the metadata extension is defacto unmaintained. But this seems simple enough, I'm happy to merge it in for you

**Comment by gr2m** [comment]
the failing tests seem legit. Tests pass on master when running `npm test` in Node 16, but fail in your branch. Can you look into that?

**Comment by ben-wilson-peak** [comment]
> the failing tests seem legit. Tests pass on master when running `npm test` in Node 16, but fail in your branch. Can you look into that?

Certainly, I'll see if I can sort that.

> sorry we are very short on maintenance time on @probot right now, and the metadata extension is defacto unmaintained. But this seems simple enough, I'm happy to merge it in for you

Appreciated that you've responded more so knowing this!

**Comment by ben-wilson-peak** [comment]
@gr2m I've updated the PR now. The tests were failing due to the change so I've instead opted to fix the regex matching and have updated the code accordingly. The tests remain unchanged.

**Pull request merged**
